#!/usr/bin/env bash
#
# A simplified docker login approach that doesn't depends on the docker binary
#
# Usage: ./docker-login <username> <password> [registry]
set -euo pipefail

username=$1
password=$2
registry=${3:-docker.io}

# Encode some funky docker heuristic
if [[ $registry = *docker.io ]]; then
  # use the v2 registry so that skopeo can do noop layer copies
  registry=https://index.docker.io/v2/
fi

mkdir ~/.docker

cat <<DOCKER_CONF > ~/.docker/config.json
{
  "auths": {
    "$registry": {
      "auth": "$(printf "%s:%s" "$username" "$password" | base64)"
    }
  }
}
DOCKER_CONF
