#!/usr/bin/env bash
#
# Usage: ./push-all <registry-prefix> <image-tag>
set -euo pipefail

registry_prefix=${1:-nixpkgs}
image_tag=${2:-latest}

releases_json=$(nix-instantiate ./release.nix --strict --eval --json)

for attr in $(echo "$releases_json" | jq -r "keys[]") ; do
  file=$(echo "$releases_json" | jq -r ".\"$attr\"")
  echo "--- $attr -> $file"
  skopeo copy "docker-archive://$file" "docker://$registry_prefix/$attr:$image_tag"
done
