#!/usr/bin/env bash
#
# Usage: ./dockerhub-image-matrix
set -euo pipefail

system_name=${NIX_SYSTEM_NAME:-x86_64-linux}

## Main ##

releases_json=$(nix-instantiate --strict --argstr system "$system_name" --eval --json)

echo "| Image / Tag | Pull |"
echo "| ---         | ---  |"

for attr in $(echo "$releases_json" | jq -r "keys[]") ; do
  name=nixpkgs/$attr
  echo -n "| [$name](https://hub.docker.com/r/$name)"
  echo -n "| \`docker pull $name\` "
  echo "|"
done
