#!/usr/bin/env bash

TESTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

for dir in "$TESTDIR"/*; do
	if [[ ! -d "$dir" ]]; then continue; fi
	attr=$(basename "$dir")
	rev=$(jq -r ".\"$attr\".rev" "$TESTDIR"/../nix/sources.json)
	sed -i "1cFROM niteo/nixpkgs-$attr:$rev AS build" "$dir"/Dockerfile
done
