#!/bin/sh -eu

mkdir ~/.docker

cat <<DOCKER_CONF > ~/.docker/config.json
{
  "auths": {
    "$CI_REGISTRY": {
      "auth": "$(printf "%s:%s" "$CI_REGISTRY_USER" "$CI_REGISTRY_PASSWORD" | base64)"
    }
  }
}
DOCKER_CONF
