#!/usr/bin/env bash
set -euo pipefail
# Arguments:
# - root directory
# - attribute to test

root=$1
out=$2
commit=$3
nixpkgsSha=$4

echo "Running tests for $out.." >&2

successCount=0
totalCount=0

echo "Loading built image into docker.." >&2
if ! image=$(docker load -i "$out" | sed -n 's/^Loaded image: \(.*\)$/\1/p'); then
  echo "Failed to load the built image into docker" >&2
  exit 1
fi
if ! docker tag "$image" base; then
  echo "Failed to tag image" >&2
  exit 1
fi
echo "Successfully loaded built image into docker" >&2

for testcase in "$root"/tests/*; do
  echo "Running testcase $testcase.." >&2
  totalCount=$(( totalCount + 1 ))

  # Copy all the test cases files into a new directory
  tmp=$(mktemp -d)
  cp -rT "$testcase" "$tmp"

  echo -n "$commit" > "$tmp"/nixpkgsCommit
  echo -n "$nixpkgsSha" > "$tmp"/nixpkgsSha

  echo "Running test.." >&2
  if ! "$testcase"/driver "$tmp"; then
    echo "Failed to run test" >&2
    continue
  fi
  echo "Successfully ran test" >&2
  echo "" >&2
  successCount=$(( successCount + 1 ))

done

echo "Finished running tests for $out, $successCount/$totalCount succeeded" >&2
if [[ "$successCount" != "$totalCount" ]]; then
  exit 1
fi

echo "" >&2
echo "" >&2
